### ISSUE TITLE
Close icon at the right top  

### ISSUE THREAD

**Issue by usamamashkoor** [rudkovskyi/videojs_popup#2]
Hi is their a way we can add a close icon at the right top the video like we have on bootstrap modal.

Thanks for the plugin btw.

**Comment by paractmol** [comment]
Hi @usamamashkoor, I am sorry for late response I haven't seen a notification. 
I think yes it should be possible, although maybe there already exists a better solution take a look here https://appleple.github.io/modal-video/

**Comment by usamamashkoor** [comment]
Thanks @rudkovskyi
